# Generated by Django 2.1.7 on 2019-04-17 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('serialization_data', models.DateTimeField(blank=True, null=True)),
                ('used_data', models.DateTimeField(blank=True, null=True)),
                ('type_package', models.CharField(max_length=120)),
                ('state', models.TextField(choices=[('Clean', 'Clean'), ('Dirty', 'Dirty')], default='Dirty')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
                ('patient', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
    ]
