# Generated by Django 2.1.7 on 2019-03-26 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('serialization_data', models.DateTimeField(blank=True, null=True)),
                ('used_data', models.DateTimeField(blank=True, null=True)),
                ('type_package', models.CharField(max_length=120)),
                ('state', models.TextField(choices=[('Clean', 'Clean'), ('Dirty', 'Dirty')], default='Dirty')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patient.Patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
            ],
        ),
    ]
