# Generated by Django 2.1.7 on 2019-03-11 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='addition_data',
        ),
        migrations.RemoveField(
            model_name='package',
            name='serialization_number',
        ),
        migrations.RemoveField(
            model_name='package',
            name='use_data',
        ),
        migrations.AddField(
            model_name='package',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='serialization_data',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 19, 57, 53, 448264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='package',
            name='state',
            field=models.TextField(choices=[('Clean', 'Clean'), ('Dirty', 'Dirty')], default='Dirty'),
        ),
    ]
