# Generated by Django 2.1.7 on 2019-03-11 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_auto_20190311_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='patient',
        ),
        migrations.AlterField(
            model_name='package',
            name='serialization_data',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 19, 59, 41, 639060, tzinfo=utc)),
        ),
    ]
