# Generated by Django 2.1.7 on 2019-05-30 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('package_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
                ('package_type', models.ManyToManyField(to='package_type.PackageType')),
            ],
        ),
    ]
